package com.strandls.user;

public class Constants {
	
	public static enum SUCCESS_CONSTANTS {
		TOKEN_SAVED,
		AUTHENTICATION_SUCCESSFUL,
		USER_VERIFICATION_SUCCESSFUL,
		OTP_REGENERATED,
		EMAIL_SMS_SENT,
		PASSWORD_UPDATED
	};
	
	public static enum ERROR_CONSTANTS {
		USERNAME_REQUIRED,
		PASSWORD_REQUIRED,
		VERIFICATION_MODE_REQUIRED,
		EMAIL_VERIFICATION_FAILED,
		USER_NOT_FOUND,
		INVALID_CAPTCHA,
		INVALID_ACTION,
		ACCOUNT_LOCKED,
		EMAIL_MOBILE_ALREADY_EXISTS,
		COULD_NOT_CREATE_USER,
		VERIFIED_OR_OTP_DELETED,
		OTP_ATTEMPTS_EXCEEDED,
		COULD_NOT_GENERATE_OTP,
		COULD_NOT_SEND_MAIL_SMS,
		OTP_DELETED,
		INVALID_OR_EXPIRED_OTP
	};

}
